# 标签处理
#### 将根因标记的中文转换为upload sample中的标准数字格式

熟悉数据，查看是否有空值

In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_csv("train_label.csv")
pd.isna(df).values

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [3]:
c = df.values
c

array([[670, 'rootcause3'],
       [673, 'rootcause3'],
       [675, 'rootcause3'],
       ...,
       [2981, 'rootcause3'],
       [2982, 'rootcause3'],
       [2983, 'rootcause3']], dtype=object)

新建一个array，存储各个label/root cause出现的总次数

In [5]:
new=np.zeros([c.shape[0],7])
new[:,0]=c[:,0]

In [7]:
new.shape

(1407, 7)

In [8]:
for i in range(c.shape[0]):
    if pd.isna(df).values[i,1] == False:
        # re.findall()用于找出文本中的所有根因数字
        # 通过单位矩阵特定行的相加得到这一样本的所有根因次数
        new[i,1:]=sum(    map(lambda x: np.eye(6)[int(x)-1], re.findall("\d",c[i,1]) )    ) 
new  

array([[ 670.,    0.,    0., ...,    0.,    0.,    0.],
       [ 673.,    0.,    0., ...,    0.,    0.,    0.],
       [ 675.,    0.,    0., ...,    0.,    0.,    0.],
       ...,
       [2981.,    0.,    0., ...,    0.,    0.,    0.],
       [2982.,    0.,    0., ...,    0.,    0.,    0.],
       [2983.,    0.,    0., ...,    0.,    0.,    0.]])

In [9]:
print("counts",np.sum(new[:,1:],0)) # 计算每一个根因出现的总次数
print("labeled:",len(np.nonzero(np.sum(new[:,1:],1))[0])) # 有标记根因的样本数
print("total:", len(c[:,0])) # 总共样本数

counts [ 112.   82. 1284.    0.    0.    0.]
labeled: 1407
total: 1407


In [10]:
# 保存
np.savetxt('processed_label.csv', new, delimiter=',')

In [11]:
label= pd.read_csv("processed_label.csv",header=None)
label

0    1    2    3    4    5    6
0      670.0  0.0  0.0  1.0  0.0  0.0  0.0
1      673.0  0.0  0.0  1.0  0.0  0.0  0.0
2      675.0  0.0  0.0  1.0  0.0  0.0  0.0
3      684.0  0.0  0.0  1.0  0.0  0.0  0.0
4      690.0  0.0  0.0  1.0  0.0  0.0  0.0
...      ...  ...  ...  ...  ...  ...  ...
1402  2979.0  0.0  0.0  1.0  0.0  0.0  0.0
1403  2980.0  0.0  0.0  1.0  0.0  0.0  0.0
1404  2981.0  0.0  0.0  1.0  0.0  0.0  0.0
1405  2982.0  0.0  0.0  1.0  0.0  0.0  0.0
1406  2983.0  0.0  0.0  1.0  0.0  0.0  0.0

[1407 rows x 7 columns]