# Lable Processing

In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_csv("train_label.csv")
pd.isna(df).values

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [3]:
c = df.values
c

array([[670, 'rootcause3'],
       [673, 'rootcause3'],
       [675, 'rootcause3'],
       ...,
       [2981, 'rootcause3'],
       [2982, 'rootcause3'],
       [2983, 'rootcause3']], dtype=object)

In [4]:
# create a 'new' array to store the label information
new=np.zeros([c.shape[0],7])
new[:,0]=c[:,0]

In [5]:
for i in range(c.shape[0]):
    if pd.isna(df).values[i,1] == False:
        # re.findall() finds the number in the string
        # by summing certain rows of the identity matrix, we get the root label
        new[i,1:]=sum(    map(lambda x: np.eye(6)[int(x)-1], re.findall("\d",c[i,1]) )    ) 
new  

array([[ 670.,    0.,    0., ...,    0.,    0.,    0.],
       [ 673.,    0.,    0., ...,    0.,    0.,    0.],
       [ 675.,    0.,    0., ...,    0.,    0.,    0.],
       ...,
       [2981.,    0.,    0., ...,    0.,    0.,    0.],
       [2982.,    0.,    0., ...,    0.,    0.,    0.],
       [2983.,    0.,    0., ...,    0.,    0.,    0.]])

In [6]:
print("counts",np.sum(new[:,1:],0)) # frequency of each lable
print("labeled:",len(np.nonzero(np.sum(new[:,1:],1))[0])) # number of labeled observations
print("total:", len(c[:,0])) # total observations

counts [ 112.   82. 1284.    0.    0.    0.]
labeled: 1407
total: 1407


In [7]:
np.savetxt('processed_label.csv', new, delimiter=',')